NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 25

NDefines.NCountry.STARTING_COMMAND_POWER = 50.0
NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 0.1
NDefines.NCountry.GIE_LIBERATED_NATION_DAILY_LEGITIMACY_CHANGE = 0
NDefines.NCountry.GIE_VETERAN_MANPOWER_NON_CORE_GAIN_FACTOR = 0.025
NDefines.NCountry.GIE_MAX_LEGITIMACY = 25
NDefines.NCountry.GIE_DIVISION_ATTACK_BONUS_ON_CORE = 0.1
NDefines.NCountry.GIE_DIVISION_DEFENSE_BONUS_ON_CORE = 0.1
NDefines.NCountry.GIE_DIVISION_ATTACK_BONUS_AGAINST_OCCUPIER = 0.1
NDefines.NCountry.GIE_DIVISION_DEFENSE_BONUS_AGAINST_OCCUPIER = 0.1
NDefines.NCountry.GIE_ESCAPING_DIVISIONS_EQUIPMENT_RATIO = 0.9
NDefines.NCountry.GIE_ESCAPING_DIVISIONS_AMOUNT_RATIO = 0.9
NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = 0
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0
NDefines.NCountry.WAR_SUPPORT_TENSION_IMPACT = 0
NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = -0.05
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.05
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 4
NDefines.NCountry.MAX_HEROES_BEING_KILLED_WAR_SUPPORT_IMPACT = -0.5
NDefines.NCountry.MAX_CONVOYS_BEING_RAIDED_WAR_SUPPORT_IMPACT = -0.5

NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1

NDefines.NDiplomacy.EMBARGO_NEIGHBOUR_AI_WEIGHT = -100
NDefines.NDiplomacy.EMBARGO_RECIPIENT_IS_MAJOR_AI_WEIGHT = -100
NDefines.NDiplomacy.EMBARGO_DIFFERENT_IDEOLOGY_AT_OFFENSIVE_WAR_AI_WEIGHT = -100
NDefines.NDiplomacy.EMBARGO_DIFFERENT_IDEOLOGY_AI_WEIGHT = -100

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 50.0
NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 4
NDefines.NTechnology.BASE_TECH_COST = 100

NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 21

NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 150000
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 2.0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 2.0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 2.0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 2.0
NDefines.NProduction.INFRA_MAX_CONSTRUCTION_COST_EFFECT = 0.25 		-- Building in a state with higher infrastructure will reduce the cost of shared buildings.
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 3
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 3
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 10
NDefines.NProduction.BASE_FACTORY_SPEED = 2
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 2
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 5
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10

NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.05

NDefines.NMilitary.MAX_NUM_TRAITS = 1
NDefines.NMilitary.UNIT_LEADER_TRAIT_SLOT_PER_LEVEL = {	0.0, 0.0, 0.0, 0.0, }
NDefines.NMilitary.UNIT_EXP_LEVELS = { 0.05, 0.1, 0.3, 0.6, 0.9 }
NDefines.NMilitary.ARMY_EXP_BASE_LEVEL = 2
NDefines.NMilitary.TRAINING_MAX_LEVEL = 3
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2
NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 1
NDefines.NMilitary.TRAINING_ATTRITION = 0.02
NDefines.NMilitary.UNIT_DIGIN_CAP = 5
NDefines.NMilitary.UNIT_DIGIN_SPEED = 1
NDefines.NMilitary.MAX_DIVISION_BRIGADE_WIDTH = 3
NDefines.NMilitary.MAX_DIVISION_BRIGADE_HEIGHT = 3
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 1
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 3
NDefines.NMilitary.PLANNING_MAX = 0.2
NDefines.NMilitary.DIVISION_SIZE_FOR_XP = 3
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 40
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 120
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 5
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 2
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999	
NDefines.NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT = -0.01
NDefines.NMilitary.STRATEGIC_SPEED_INFRA_BASE = 5.0
NDefines.NMilitary.STRATEGIC_SPEED_INFRA_MAX = 5.0
NDefines.NMilitary.STRATEGIC_SPEED_RAIL_BASE = 15.0
NDefines.NMilitary.STRATEGIC_SPEED_RAIL_MAX = 35.0
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.075
NDefines.NMilitary.BASE_FORT_PENALTY = -0.25
NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.15
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.3
NDefines.NMilitary.SPECIAL_FORCES_CAP_BASE = 0.05
NDefines.NMilitary.SPECIAL_FORCES_CAP_MIN = 6
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.1
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE = 0.90
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 112
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.05
NDefines.NMilitary.AIR_SUPPORT_BASE = 0.05
NDefines.NMilitary.FASTER_ORG_REGAIN_MULT = 0.5
NDefines.NMilitary.SUPPLY_ORG_MAX_CAP = 0.5
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.045
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 5
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.05
NDefines.NMilitary.PLANNING_GAIN = 0.01

NDefines.NNavy.COMBAT_MAX_GROUPS = 3
NDefines.NNavy.AMPHIBIOUS_LANDING_PENALTY = -0.4
NDefines.NNavy.SUPPLY_NEED_FACTOR = 0
NDefines.NNavy.COMBAT_MIN_HIT_CHANCE = 0.01
NDefines.NNavy.COMBAT_DAMAGE_RANDOMNESS = 0.2
NDefines.NNavy.GUN_HIT_PROFILES = { 60.0, 80.0, 40.0 }
NDefines.NNavy.CONVOY_HIT_PROFILE = 60.0
NDefines.NNavy.HIT_PROFILE_MULT = 100.0
NDefines.NNavy.HIT_PROFILE_SPEED_FACTOR = 2
NDefines.NNavy.HIT_PROFILE_SPEED_BASE = 0
NDefines.NNavy.COMBAT_DAMAGE_TO_ORG_FACTOR = 1.2
NDefines.NNavy.COMBAT_MAX_GROUPS = 3
NDefines.NNavy.COMBAT_DETECTED_CONVOYS_FROM_SURFACE_DETECTION_STAT = 0.05
NDefines.NNavy.NAVY_PIERCING_THRESHOLDS = { 2.00, 1.00, 0.75, 0.50, 0.25, 0.10, 0.00 }
NDefines.NNavy.MISSION_SUPREMACY_RATIOS = { 0.0, 1.0, 0.0, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0 }
NDefines.NNavy.DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.75
NDefines.NNavy.SCREENING_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING	= 1.0
NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING	= 0.9
NDefines.NNavy.SUBMARINE_REVEAL_ON_MINIMUM_POSITIONING = 2.0
NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 2.0
NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS 	= 0.25
NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CARRIERS = 1.0
NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.1
NDefines.NNavy.NAVALBASE_REPAIR_MULT = 0.03
NDefines.NNavy.SUPREMACY_PER_SHIP_PER_MANPOWER = 0.1

NDefines.NCharacter.SPECIALIST_ADVISOR_MIN_RANK = 2
NDefines.NCharacter.EXPERT_ADVISOR_MIN_RANK = 3
NDefines.NCharacter.GENIUS_ADVISOR_MIN_RANK = 5
NDefines.ADVISOR_PROMOTION_COST = 50
NDefines.DEFAULT_PP_COST_FOR_MILITARY_ADVISOR = 50

NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.1
NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.15
NDefines.NSupply.SUPPLY_FROM_DAMAGED_INFRA = 0.35
NDefines.NSupply.AVAILABLE_MANPOWER_STATE_SUPPLY = 0.4
NDefines.NSupply.NON_CORE_MANPOWER_STATE_SUPPLY = 0.3

NDefines.NRailwayGun.RAILWAY_GUN_RANGE = 25
NDefines.NRailwayGun.ATTACK_TO_FORTS_MODIFIER_FACTOR = 1
NDefines.NRailwayGun.ATTACK_TO_ENTRENCHMENT_MODIFIER_FACTOR = 0.1
NDefines.NRailwayGun.ATTACK_TO_BOMBARDMENT_MODIFIER_FACTOR = 0.2

NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 100
NDefines.NResistance.SUPPRESSION_NEEDED_BY_RESISTANCE_POINT = 0.5
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_IS_EXILE_MIN = 0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_IS_EXILE_MAX = 0

NDefines.NIntel.STATIC_INTEL_SOURCE_INTEL_NETWORK_MAXIMUMS = { 30.0, 30.0, 30.0, 30.0 }